// Code generated by tygor; DO NOT EDIT.
//go:build skeleton

package environment

import (
	"errors"
	"go.k6.io/k6/js/modules"
)

// init invokes module registration.
func init() {
	register(newModule)
}

// newModule returns new goModuleImpl instance.
func newModule(_ modules.VU) goModule {
	return new(goModuleImpl)
}

// goModuleImpl is an empty implementation of goModule.
type goModuleImpl struct{}

var _ goModule = (*goModuleImpl)(nil)

// newEnvironment is a goModule method implementation.
func (self *goModuleImpl) newEnvironment(nameArg string, typeArg string, initFolderArg string) (goEnvironment, error) {
	return nil, errors.ErrUnsupported
}

// defaultEnvironmentGetter is a goModule property getter method implementation.
func (self *goModuleImpl) defaultEnvironmentGetter() (goEnvironment, error) {
	return nil, errors.ErrUnsupported
}

// goEnvironmentImpl is an empty implementation of goEnvironment.
type goEnvironmentImpl struct{}

var _ goEnvironment = (*goEnvironmentImpl)(nil)

// initMethod is a goEnvironment method implementation.
func (self *goEnvironmentImpl) initMethod() (interface{}, error) {
	return nil, errors.ErrUnsupported
}

// deleteMethod is a goEnvironment method implementation.
func (self *goEnvironmentImpl) deleteMethod() (interface{}, error) {
	return nil, errors.ErrUnsupported
}

// applyMethod is a goEnvironment method implementation.
func (self *goEnvironmentImpl) applyMethod(fileArg string) error {
	return errors.ErrUnsupported
}

// applySpecMethod is a goEnvironment method implementation.
func (self *goEnvironmentImpl) applySpecMethod(specArg string) error {
	return errors.ErrUnsupported
}

// waitMethod is a goEnvironment method implementation.
func (self *goEnvironmentImpl) waitMethod(conditionArg interface{}, optsArg interface{}) (interface{}, error) {
	return nil, errors.ErrUnsupported
}
