apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev
  name: app
  namespace: amazing-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - image: nginx
        name: nginx