name: CI
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    uses: grafana/k6-ci/.github/workflows/all.yml@a6b831b4cc3edb31b02eea2cd275963cd4a9ea8b # main
